import test from 'node:test';
import assert from 'node:assert/strict';
import {deriveKey,seal,unseal,validateEnvelope,KDF_ITERATIONS,base64,unbase64} from '../../src/lib/crypto.js';
import {emptyData,capture} from '../../src/domain/model.js';
import {today} from '../../src/domain/dates.js';
import {Vault} from '../../src/lib/storage.js';
const pw='僅供測試的完整長密語 test 2026';
const salt=crypto.getRandomValues(new Uint8Array(16)), key=await deriveKey(pw,salt);
const data=capture(emptyData(),today(),'marked');
const envelope=await seal(data,key,salt);
test('AES-GCM encrypted roundtrip preserves complete validated payload',async()=>{assert.deepEqual((await unseal(envelope,pw)).data,data);assert.ok(!JSON.stringify(envelope).includes('records'));});
test('600000 iteration PBKDF2 key is nonextractable',()=>{assert.equal(KDF_ITERATIONS,600000);assert.equal(key.extractable,false);});
test('every sealing gets fresh IV and ciphertext',async()=>{const other=await seal(data,key,salt,envelope.revision,envelope.id);assert.notEqual(other.iv,envelope.iv);assert.notEqual(other.ciphertext,envelope.ciphertext);});
test('wrong passphrase never decrypts',async()=>{await assert.rejects(()=>unseal(envelope,'another wrong long password'));});
test('revision and vault identity are authenticated',async()=>{await assert.rejects(()=>unseal({...envelope,revision:1},pw));await assert.rejects(()=>unseal({...envelope,id:crypto.randomUUID()},pw));});
test('corrupted ciphertext fails authentication',async()=>{const b=unbase64(envelope.ciphertext);b[5]^=1;await assert.rejects(()=>unseal({...envelope,ciphertext:base64(b)},pw));});
test('unsupported KDF prevents expensive attacker-chosen work',()=>assert.throws(()=>validateEnvelope({...envelope,iterations:999999999})));
test('malformed base64 and short IV are rejected',()=>{assert.throws(()=>unbase64('%%%'));assert.throws(()=>validateEnvelope({...envelope,iv:base64(new Uint8Array(11))}));});
test('short passwords rejected; spaces and Chinese accepted',async()=>{await assert.rejects(()=>deriveKey('short',salt));assert.ok(key);});
test('demo writes are serializable and do not invoke persistent IndexedDB',async()=>{const v=new Vault();v.startDemo();await Promise.all([v.update(d=>{d.settings.word='第一';return d;}),v.update(d=>{d.settings.word+='第二';return d;})]);assert.equal(v.data.settings.word,'第一第二');await assert.rejects(()=>v.backup());});
test('locking cancels queued writes and clears key references',async()=>{const v=new Vault();v.startDemo();const write=v.update(d=>d);v.lock();await assert.rejects(()=>write);assert.equal(v.key,null);assert.equal(v.data,null);});
